export const seasonalEvents: { [month: number]: string[] } = {
  0: [
    // January
    'new-year',
    'winter',
    'snow',
    'skiing',
    'january-sales',
    'australia-day',
    'mlk-day',
    'cold-weather',
    'fireplace',
    'ice-skating',
    'hot-chocolate',
    'national-mentoring-month',
    'resolutions',
    'northern-lights',
    'polar-bear-plunge',
  ],
  1: [
    // February
    'valentines-day',
    'winter',
    'chocolate',
    'super-bowl',
    'groundhog-day',
    'black-history-month',
    'mardi-gras',
    'lunar-new-year',
    'carnival',
    'ice-fishing',
    'romance',
    'heart-health',
    'snowboarding',
    'cozy-evenings',
    'snow-sculptures',
  ],
  2: [
    // March
    'spring',
    'st-patricks-day',
    'green',
    'rain',
    'international-womens-day',
    'daylight-savings',
    'pi-day',
    'holi',
    'purim',
    'spring-cleaning',
    'blooming-flowers',
    'planting-season',
    'hiking',
    'world-water-day',
    'cherry-blossoms',
  ],
  3: [
    // April
    'easter',
    'spring',
    'flowers',
    'rebirth',
    'earth-day',
    'passover',
    'ramadan',
    'cherry-blossom-season',
    'gardening',
    'outdoor-picnics',
    'spring-showers',
    'nature-walks',
    'arbor-day',
    'baseball-season',
    'daffodils',
  ],
  4: [
    // May
    'spring',
    'labor-day',
    'gardening',
    'may-day',
    'memorial-day',
    'cinco-de-mayo',
    'mother’s-day',
    'graduation',
    'birdwatching',
    'early-summer',
    'sunny-days',
    'wildflowers',
    'outdoor-markets',
    'bees-and-pollination',
    'bicycling',
  ],
  5: [
    // June
    'summer',
    'pride',
    'vacation',
    'beaches',
    'fathers-day',
    'juneteenth',
    'weddings',
    'camping',
    'swimming',
    'barbecues',
    'long-days',
    'music-festivals',
    'wildlife-safaris',
    'pool-parties',
    'solstice',
  ],
  6: [
    // July
    'summer',
    'independence-day',
    'barbecue',
    'fireworks',
    'picnics',
    'beach-volleyball',
    'travel',
    'hot-weather',
    'campfires',
    'hiking',
    'lemonade-stands',
    'family-reunions',
    'outdoor-concerts',
    'national-parks',
    'road-trips',
  ],
  7: [
    // August
    'summer',
    'travel',
    'outdoors',
    'back-to-school-prep',
    'beach-vacations',
    'stargazing',
    'sunsets',
    'farmers-markets',
    'ice-cream',
    'summer-reading',
    'lazy-days',
    'wildflowers',
    'canoeing',
    'sunflower-fields',
    'fruit-picking',
  ],
  8: [
    // September
    'fall',
    'harvest',
    'autumn',
    'back-to-school',
    'labor-day',
    'apple-picking',
    'changing-leaves',
    'cozy-sweaters',
    'pumpkin-spice',
    'football-season',
    'bonfires',
    'corn-mazes',
    'fall-fairs',
    'late-summer',
    'hayrides',
  ],
  9: [
    // October
    'halloween',
    'fall',
    'pumpkins',
    'costumes',
    'harvest-festivals',
    'spooky-season',
    'autumn-leaves',
    'horror-movies',
    'ghost-stories',
    'trick-or-treat',
    'candles',
    'witchcraft',
    'haunted-houses',
    'hot-cider',
    'scarecrows',
  ],
  10: [
    // November
    'thanksgiving',
    'fall',
    'family',
    'feasting',
    'black-friday',
    'cozy-evenings',
    'autumn-hikes',
    'firewood',
    'sweater-weather',
    'gratitude',
    'cranberries',
    'pie-baking',
    'comfort-food',
    'friendsgiving',
    'heritage-month',
  ],
  11: [
    // December
    'holiday',
    'christmas',
    'hanukkah',
    'kwanzaa',
    'winter',
    'new-years-eve',
    'snowfall',
    'gift-giving',
    'festive-lights',
    'cozy-socks',
    'hot-cocoa',
    'caroling',
    'family-gatherings',
    'holiday-baking',
    'wreath-making',
  ],
};
